### PR TITLE
feat: add rewrite option

### PR DESCRIPTION
**Pull request by trim21**
https://github.com/golangci/golangci-lint/issues/3171

this PR add a `func RunRewrite(filename string, needSimplify bool, rewrite string) ([]byte, error)` to support `gofmt`'s `-r` flag.

The caller from `golangci-lint` will use newly added method `RunRewrite` to apply a option rewrite rule.

empty string as `rewrite` will be ignored.

private methods are added because origin impl has `os.Exit(...)`

### CODE REVIEW

**Comment by ldez** [comment]
Can you add a real PR description?

**Comment by trim21** [comment]
@ldez done

**Comment by ldez** [comment]
When a PR is not ready:
- work locally before opening it
- open your PR as draft

When a PR is open, a review can start, each commit after the opening of the PR requires another review.

Fixing a typo or adding a comment is not a problem but 2600dff is not expected 2 hours after the opening of the PR.

**Comment by trim21** [comment]
sorry, it's ready to be reviewed now.

**Comment by ldez** [comment]
:warning:  I will merge this PR but please don't open a PR on golangci-lint because I would like to change other stuff. :warning:

**Pull request merged**
